name: Deploy Android App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup JAVA
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Creating debug APK
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebug

      - name: Sign Android debug release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          alias: ${{ secrets.ANDROID_KEYALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
      
      - name: Upload Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: Debug Artifacts
          path: app/build/outputs/apk/*.apk

      

  deploy-to-appcenter:
    runs-on: macos-10.15
    needs: [build]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Debug Artifacts

      - name: upload artefact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: cchanka/android-github-actions-test
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: Collaborators
          file: app-prod-debug-signed.apk
          notifyTesters: true
          debug: false